### PR TITLE
ServeDir to call fallback for invalid filenames (fixes #573)

### LINKED ISSUE #573: %00 sequence in path returns ISE (even though the problem is in request)
- [x] I have looked for existing issues (including closed) about this

### Version

tower-http v0.6.4

### Platform

`Linux silmeth-laptop 6.14.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Sun Apr  6 15:05:05 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux`

### Description

When `ServeDir` service gets requests with the sequence `%00` (percent-encoded null byte) in the path (eg. `/app/%00/foo.xml`), it returns status code `500` Internal Server Error – suggesting there is a problem with the server’s file system, but fault is in the request (invalid file path character encoded in the request’s path).

It also logs this prints this problem to the log:
```
tower_http::services::fs::serve_dir: Failed to read file error=file name contained an unexpected NUL byte
```

I would expect it to return some 4xx bad request status instead.

### PR DESCRIPTION
**Pull request by aryaveersr**
## Motivation

( See #573 )

ServeDir currently returns ISE for any request involving invalid filenames (eg: `/path|name/`). This fixes it so that it instead forwards the request to the fallback (as it should).

## Solution

This uses a rather ugly solution of manually checking Raw OS error codes for windows. If we ever upgrade MSRV to 1.87 or beyond, we should instead use `io::ErrorKind::InvalidFilename` (stabilized in 1.87). I've also put a comment with FIXME regarding this.

### CODE REVIEW

File: tower-http/src/services/fs/serve_dir/future.rs [hunk 1]
```diff
@@ -105,7 +105,7 @@ where
                         break Poll::Ready(Ok(res));
                     }
 
-                    Ok(OpenFileOutput::FileNotFound) => {
+                    Ok(OpenFileOutput::FileNotFound) | Ok(OpenFileOutput::InvalidFilename) => {
```
Comment (jplatte) [inline tower-http/src/services/fs/serve_dir/future.rs:108]:
```suggestion
                    Ok(OpenFileOutput::FileNotFound | OpenFileOutput::InvalidFilename) => {
```

**Review by jplatte — APPROVED** [review]
Thanks!
