### PR TITLE
Parse accept header with quotes

### LINKED ISSUE #291: ValidateRequest: Accept header parsing is incorrect
Turns out parsing the `Accept` header isn't just a matter of splitting on commas, like we do [here](https://github.com/tower-rs/tower-http/blob/master/tower-http/src/validate_request.rs#L387).

See https://github.com/http-rs/http-types/issues/349 for more details.

### PR DESCRIPTION
**Pull request by 82marbag**
Closes #291.

This is a preview. https://github.com/hyperium/mime/pull/145 needs to go first.

### CODE REVIEW

**Comment by 82marbag** [comment]
The commit in `mime` has been merged. Can these checks here be restarted?

**Comment by 82marbag** [comment]
> The commit in `mime` has been merged. Can these checks here be restarted?

It was not published to crates.io, sorry. v0.3.17 is out now, can you restart them again please?

**Comment by seanmonstar** [comment]
It'd probably be best to set the minimum version of mime that is needed.

File: tower-http/src/validate_request.rs [hunk 1]
```diff
@@ -379,12 +379,7 @@ where
             .headers()
             .get_all(header::ACCEPT)
             .into_iter()
-            .flat_map(|header| {
-                header
-                    .to_str()
-                    .ok()
-                    .into_iter()
-            })
+            .flat_map(|header| header.to_str().ok().into_iter())
```
Comment (jplatte) [inline tower-http/src/validate_request.rs:382]: This does the same thing and is easier to understand at a glance.

```suggestion
            .filter_map(|header| header.to_str().ok())
```

File: tower-http/src/validate_request.rs [hunk 2]
```diff
@@ -379,25 +379,24 @@ where
...
+                                (t, s) if t == typ && s == subtype => true,
+                                (t, mime::STAR) if t == typ => true,
+                                (mime::STAR, mime::STAR) => true,
+                                _ => false,
+                            }
+                        } else {
+                            false
                         }
                     })
+                    .reduce(|acc, mim| acc || mim)
```
Comment (Nehliin) [inline tower-http/src/validate_request.rs:399]: Do we not want all to be true here?

Comment (82marbag) [reply tower-http/src/validate_request.rs:399]: We want to find one matching accept, right?

File: tower-http/src/validate_request.rs [hunk 3]
```diff
@@ -545,6 +544,25 @@ mod tests {
         assert_eq!(res.status(), StatusCode::OK);
     }
 
+    #[tokio::test]
+    async fn accepted_header_with_quotes() {
```
Comment (Nehliin) [inline tower-http/src/validate_request.rs:548]: Unless I'm misunderstanding the expected behavior here for the quoted values it would perhaps be nice with an additional test that ensures for example this doesn't pass:

Validate:
``"parisien=\"baguette, jambon, fromage\""``

Incoming req:
`"parisien=\"baguette\""`

Perhaps one variant with vice versa as well

**Review by Nehliin — COMMENTED** [review]
LGTM but I think we can add some more tests than just one for were the strings identically match each other. The current test could still pass even if the `parisien` value started to become parsed/handled incorrectly

File: tower-http/src/validate_request.rs (hunk 3 above)
Comment (82marbag) [reply tower-http/src/validate_request.rs]: I've updated the tests: currently we don't look at the weight, but splitting by `,` would have allowed `text/html` in `parisien=\"baguette, jambon, text/html, fromage\"`. The `mime` iterator handles quoted strings. Does it make more sense now?

**Review by Nehliin — APPROVED** [review]
thanks!

**Comment by jplatte** [comment]
Are we waiting on @davidpdrsn or why is this not merged yet? :)

**Comment by 82marbag** [comment]
Anything to do here?

**Comment by 82marbag** [comment]
@Nehliin @jplatte @davidpdrsn let me know if there are missing items before merging
